### ISSUE TITLE
Support a refresh token parameter to skip the OAuth redirect and allow automation

### ISSUE THREAD

**Issue by leavengood** [crewjam/awsconsoleauth#1]
The first time a user approves the OAuth connection with Google there are usually three major pieces of response data:
- The access token.
- The expiration date of the access token.
- A refresh token which can be saved to get new access tokens when they expire.

AWSConsoleAuth should display the user's refresh token in the response so they can save it. Then if that refresh token is provided as a parameter it is used to get a new access token rather than requiring the user to go through the OAuth process. This means scripts can get a new AWS token without needing a browser or the user to intervene.

**Comment by crewjam** [comment]
:+1:
